 5 Functions that you need to know in pytorch.

An short introduction about PyTorch and about the chosen functions. 

- torch.bitwise_and
- torch.arange
- torch.narrow
- torch.exp
- torch.chunk

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.bitwise_and(pointwise operations)

Computes the bitwise and operation on two given tensors.


In [4]:
# Example 1 - working (change this)
torch.bitwise_and(torch.tensor([2, 1, -4], dtype=torch.int8), torch.tensor([5, -1, 2], dtype=torch.int8))

tensor([0, 1, 0], dtype=torch.int8)

Explanation about example:- The above example returns 0,1,0 after applying bitwise AND between (2,5), (1,-1), and (-4,2).

In [3]:
# Example 2 - working
torch.bitwise_and(torch.tensor([True,False]), torch.tensor([False,True]))

tensor([False, False])

Explanation about example:- This example Takes tensor values and returned boolean by applying Logical AND between those two values.

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
torch.bitwise_and(torch.tensor([1., 2.,4.], dtype=torch.float32), torch.tensor([3., 4., 5.], dtype=torch.float32))

RuntimeError: ignored

Explanation about example:- This function do not implement float values as these values are not casted into desired output type which is long and gives RUNTIME ERROR.

Closing comments about when to use this function:- This function is used when we want to find bitwise or logical AND between tensors.

Let's save our work using Jovian before continuing.

In [10]:
!pip install jovian --upgrade --quiet

In [11]:
import jovian

In [14]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/vardhanyash20000/01-tensor-operations


'https://jovian.ai/vardhanyash20000/01-tensor-operations'

## Function 2 -torch.arange(creation operations)
 This function arranges the values between two digit with the difference mentioned with inputs.

In [16]:
# Example 1 - working
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Explanation about example:- It generated the values by default starting from 0 upto n-1(which is 10 in this case)

In [17]:
# Example 2 - working
torch.arange(5,90,5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

Explanation about example:- Here the start value is 5(included in result) the ending value is 90(which is not included as it displays n-1) and the difference between values is 5.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(5,3,1)

RuntimeError: ignored

Explanation about example:- Starting value can never be greater than end value unless the difference is negative which implies that it is counting backwards.

Closing comments about when to use this function:- This finction is used when we want to have values at constant intervals.

In [19]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/vardhanyash20000/01-tensor-operations


'https://jovian.ai/vardhanyash20000/01-tensor-operations'

## Function 3 - torch.narrow(Indexing,Slicing,Mutating operations)

Add some explanations:- Returns a narrowed version of input tensor

In [22]:
# Example 1 - working
t=torch.tensor([[5, 2, 7], [5, 0, 6], [7, 12, 14]])
torch.narrow(t,0,0,2)

tensor([[5, 2, 7],
        [5, 0, 6]])

Explanation about example:-The tensor t is narrowed along the dimension = 0 starting from the index position start = 0 to ending start+length = 2+0 = 2, with excluding the ending.

In [23]:
# Example 2 - working
torch.narrow(t,1,1,2)

tensor([[ 2,  7],
        [ 0,  6],
        [12, 14]])

Explanation about example:-here the dimension was 1 which resulted into slicing of 1 element from each and remaining two were saved including the ending.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
torch.narrow(t,1,1,3)

RuntimeError: ignored

Explanation about example:- Here we can see the start+length exceeded the maximum index and it throws runtime error.

Closing comments about when to use this function:-This function can be used to slice larger tensors without writing the dimension directly and not using : .

In [25]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/vardhanyash20000/01-tensor-operations


'https://jovian.ai/vardhanyash20000/01-tensor-operations'

## Function 4 - torch.exp(Pointwise operations)

Add some explanations:-Computes the base two exponential function of input.

In [30]:
# Example 1 - working
t=torch.tensor([6.2,0])
torch.exp(t)

tensor([492.7490,   1.0000])

Explanation about example:-It takes values as power of e and returns the result.

In [32]:
# Example 2 - working
import math
torch.exp(torch.tensor([0, math.log(2.)]))

tensor([1., 2.])

Explanation about example:-Logarithmic function with base e if raised as a power of e then it simply returns the value which is passed through log function.


In [33]:
# Example 3 - breaking (to illustrate when it breaks)
x=torch.tensor([a])
torch.exp(x)

NameError: ignored

Explanation about example:- Function is limited to certain values.

Closing comments about when to use this function:- It is used when you want to get exponential values of attributes.

In [34]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/vardhanyash20000/01-tensor-operations


'https://jovian.ai/vardhanyash20000/01-tensor-operations'

## Function 5 - torch.chunk(Indexing, Slicing, Mutating operations)

Add some explanations:- Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.

In [35]:
# Example 1 - working
tensor1 = torch.arange(0, 15, 2)
print(tensor1)
torch.chunk(tensor1, 3)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])


(tensor([0, 2, 4]), tensor([ 6,  8, 10]), tensor([12, 14]))

Explanation about example:- Here we see first we created tensor1 and then using chunk function splited it into 3 parts here we can see last part has only two values instead of three like other two that is because tensor one has odd number of total values.

In [37]:
# Example 2 - working
tensor2 = torch.arange(0, 50, 2)
print(tensor2)
torch.chunk(tensor2, 3, 0)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48])


(tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16]),
 tensor([18, 20, 22, 24, 26, 28, 30, 32, 34]),
 tensor([36, 38, 40, 42, 44, 46, 48]))

Explanation about example:-Here we created a tensor2, then we created 3 chunks and please note that the last tensor has two less element than the rest.

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
torch.chunk(tensor2,3,1.0)

TypeError: ignored

Explanation about example:- Dimension along which we want to split will always be an integer and cannot be a float value.

Closing comments about when to use this function:- This function can be used to modify the data of the tensors as we want.

In [39]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/vardhanyash20000/01-tensor-operations


'https://jovian.ai/vardhanyash20000/01-tensor-operations'

## Conclusion

In this notebook we covered implementations of few basic but useful functions of pytorch, there are a alot of things that can be done with the help of these functions and many more available in pyt 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
